version: "2"

linters:
  # default enables: errcheck, govet, ineffassign, staticcheck, unused
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/gauthierbraillon/ensemble

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
