version: 2

builds:
  - binary: ensemble
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ["-s -w -X github.com/gauthierbraillon/ensemble/cmd.Version={{.Version}}"]

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude: ['^docs:', '^chore:']
